name: crip_dart
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  encrypt: ^5.0.3
  flat_buffers: ^23.5.26
  pointycastle: ^3.9.1

dev_dependencies:
  http_mock_adapter: ^0.6.1
  lints: ^4.0.0
  test: ^1.24.0
